from schema import Edge, GraphResponse, Message, Node

seed_data = GraphResponse(
    nodes=[
        Node(
            id="mp_neuron",
            kind="paper",
            label="McCulloch–Pitts",
            year=1943,
            category="foundations",
            summary="First mathematical model of a neuron as a logical gate — the seed of every neural network to come.",
            x=159,
            y=374,
        ),
        Node(
            id="perceptron",
            kind="paper",
            label="Perceptron",
            year=1958,
            category="foundations",
            summary="Rosenblatt's first trainable neural network, learning from real data.",
            x=403,
            y=374,
        ),
        Node(
            id="backprop",
            kind="paper",
            label="Backpropagation",
            year=1986,
            category="foundations",
            summary="Rumelhart, Hinton, Williams — the algorithm that finally trained deep networks.",
            x=859,
            y=374,
        ),
        Node(
            id="cnn",
            kind="paper",
            label="LeNet · CNN",
            year=1989,
            category="vision",
            summary="LeCun — convolutional layers that read images by sliding learned filters.",
            x=908,
            y=144,
        ),
        Node(
            id="lstm",
            kind="paper",
            label="LSTM",
            year=1997,
            category="language",
            summary="Hochreiter & Schmidhuber — solved the vanishing-gradient problem in recurrent nets.",
            x=1038,
            y=576,
        ),
        Node(
            id="word2vec",
            kind="paper",
            label="word2vec",
            year=2013,
            category="language",
            summary="Mikolov — turning words into semantic vectors you could do arithmetic on.",
            x=1299,
            y=576,
        ),
        Node(
            id="seq2seq",
            kind="paper",
            label="Seq2Seq",
            year=2014,
            category="language",
            summary="Sutskever — an encoder/decoder pair for machine translation.",
            x=1315,
            y=576,
        ),
        Node(
            id="attention",
            kind="paper",
            label="Bahdanau Attention",
            year=2014,
            category="language",
            summary="Bahdanau — letting the decoder look back at every part of the source.",
            x=1330,
            y=520,
        ),
        Node(
            id="transformer",
            kind="paper",
            label="Transformer",
            year=2017,
            category="architecture",
            summary="Vaswani et al. — Attention Is All You Need. The substrate of every modern LLM.",
            x=1200,
            y=460,
        ),
        Node(
            id="bert_gpt",
            kind="paper",
            label="BERT · GPT",
            year=2018,
            category="language",
            summary="Massive pre-training on raw text. The opening of the large-language-model era.",
            x=1381,
            y=576,
        ),
    ],
    edges=[
        Edge(from_node="mp_neuron", to="perceptron", type="extends"),
        Edge(from_node="perceptron", to="backprop", type="enables"),
        Edge(from_node="backprop", to="cnn", type="applies"),
        Edge(from_node="backprop", to="lstm", type="applies"),
        Edge(from_node="lstm", to="seq2seq", type="uses"),
        Edge(from_node="word2vec", to="seq2seq", type="inspired_by"),
        Edge(from_node="seq2seq", to="attention", type="extends"),
        Edge(from_node="attention", to="transformer", type="extends"),
        Edge(from_node="transformer", to="bert_gpt", type="extends"),
    ],
    messages=[
        Message(
            role="assistant",
            content=(
                "Welcome to your notebook. This is a living chart of how machines learned to think. "
                "Ask me about any idea, person, or paper — I'll explain it and draw it onto the map. "
                "The things we discuss will become annotations in the margins of each node."
            ),
        ),
    ],
)
